#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=01:00:00
#PBS -N app-synthsr

#set -e
#set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.3.2 ./synthsr.sh
